[package]
name = "wasm_contract_sglk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer = "=4.2.4"
anyhow = "1.0.81"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
